### ISSUE TITLE
Fix old-style numbers in tables

### ISSUE THREAD

**Issue by kjgarza** [datacite/segugio#6]
Raleway numberals are old-style and that doesn't look good in tables, e.g. at https://stats.datacite.org. We ought to consider a new font or a fix such as https://h-ibaldo.github.io/Raleway_Fixed_Numerals/.

**Comment by mfenner** [comment]
Instead of using a different font we can also use CSS to generate lining numerals for Raleway: https://medium.com/@imran_parvez/mending-flipkarts-typography-1-910207a77cce

**Comment by richardhallett** [comment]
After a bit of research the problem is we can't use the CSS font lining selector code to make this work, reason being is that google fonts has basically minified this for us and does not support this option, some people suggest what we are doing with subset=all but I do not believe that actually works.
If we were managing the opentype raleway font ourselves then we could use the CSS fix.

Long term we might want to consider changing to a different font, but if we want to use Raleway, other people suggest just having a subset font that is for just numbers, like Roboto. 

Raleway isn't actually broken it's just by design, so using a different one with "fixed" numbers probably isnt right either, I'd say new font entirely or we work around it for numbers in places like tables.

For now I've created a PR to just set anywhere we use tables and the number class to be use Arial as this is a pretty standard fallback and we don't have to load in any new fonts.
